### ISSUE TITLE
Lookup failing on binary files

### ISSUE THREAD

**Issue by vlcinsky** [devsnd/tarindexer#3]
When binary files (e.g. xml.gz) are in archive, printing content to console fails as it is unable to convert some bytes to ASCII.

Command concept shall be probably changed and try to write directly to a file (possibly using the lookup name).

Be careful, it may contain path, which does not exist yet.

Other note: tar, when extracting files, tries to preserve all the attributes. But for this utility it seems fine to ignore such behaviour.

**Comment by ReactorScram** [comment]
I have the same problem. I don't know what the point is of doing an ASCII decoding? Archiving tools are usually agnostic of text encoding.

I modified it to print directly to stdout, it seems to work fine for both ASCII and binary data. (I extracted a JPEG just fine with ```tarindexer -l tarfile.tar indexfile.index lookuppath > picture.jpeg```)

Should I make a PR?

**Comment by devsnd** [comment]
@ReactorScram Yeah, sure go for it!

**Comment by ReactorScram** [comment]
I don't know if it sent you a notice or something, but I made the PR.

**Comment by devsnd** [comment]
Ah yeah, sorry, I didn't get the notification for the PR, its now merged, thanks!
